---
exp_name: di  # 0417
exp_dir: ../exp
device: 'cpu' # 'mps' in M1 Mac
seed: None # If you want to reproduce set the seed
model_name:  # NCF, NCF_p
train_resume: False

dataset:

train:
    optimizer: Adam
    epoch: 100
    lr: 1.0e-3
    wd: 0.0e-4 # Adam
    momentum: 0.9 # SGD
    batch_size : 32


dimenet:
  hidden_channels: 128
  out_channels: 1
  num_blocks: 6
  int_emb_size: 64
  basis_emb_size: 8
  out_emb_channels: 256
  num_spherical: 7
  num_radial: 6
  cutoff: 5.0
  max_num_neighbors: 32
  envelope_exponent: 5
  num_before_skip: 1
  num_after_skip: 2
  num_output_layers: 3